name: Iron Learning
favicon: null
layout_spectrum: 0.8524617080111057
typography_spectrum: 0.838069116929546
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4287695363163948
  lightness: 0.7141209167893976
  saturation: 0.5452101717237383
  rhythmicContrast: 0.08996227197349072
purpose: []
