name: Iron Learning
favicon: null
layout_spectrum: 0.8524617080111057
typography_spectrum: 0.21339818323031068
title: Live a life less ordinary
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.21829242981038988
  lightness: 0.8939835876226425
  saturation: 0.5543119658250362
  rhythmicContrast: 0.38367794547230005
purpose: []
