typography_spectrum: 0.6200982863083482
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.21829242981038988
  lightness: 0.8939835876226425
  saturation: 0.5543119658250362
  rhythmicContrast: 0.38367794547230005
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.607583139790222
analytics:
  google: null
  facebook: null
  twitter: null
name: Iron Learning
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
purpose: []
